// <auto-generated />
using System;
using GraphQL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GraphQL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260120053117_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GraphQL.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.HasIndex("ManagerId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "789 Pine Rd, San Francisco, CA",
                            ContactNumber = "+1-555-0201",
                            CreatedAt = new DateTime(2026, 1, 20, 5, 31, 17, 171, DateTimeKind.Utc).AddTicks(9265),
                            CreatedBy = "System",
                            Department = "Engineering",
                            Email = "alice.johnson@company.com",
                            EmployeeCode = "EMP001",
                            FirstName = "Alice",
                            FullName = "Alice Johnson",
                            HireDate = new DateTime(2022, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LastName = "Johnson",
                            ManagerId = 1,
                            Position = "Senior Developer",
                            Salary = 95000m
                        },
                        new
                        {
                            Id = 2,
                            Address = "321 Elm St, Seattle, WA",
                            ContactNumber = "+1-555-0202",
                            CreatedAt = new DateTime(2026, 1, 20, 5, 31, 17, 171, DateTimeKind.Utc).AddTicks(9295),
                            CreatedBy = "System",
                            Department = "Engineering",
                            Email = "bob.wilson@company.com",
                            EmployeeCode = "EMP002",
                            FirstName = "Bob",
                            FullName = "Bob Wilson",
                            HireDate = new DateTime(2023, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LastName = "Wilson",
                            ManagerId = 1,
                            Position = "Junior Developer",
                            Salary = 65000m
                        },
                        new
                        {
                            Id = 3,
                            Address = "654 Maple Dr, Boston, MA",
                            ContactNumber = "+1-555-0203",
                            CreatedAt = new DateTime(2026, 1, 20, 5, 31, 17, 171, DateTimeKind.Utc).AddTicks(9298),
                            CreatedBy = "System",
                            Department = "Marketing",
                            Email = "carol.martinez@company.com",
                            EmployeeCode = "EMP003",
                            FirstName = "Carol",
                            FullName = "Carol Martinez",
                            HireDate = new DateTime(2021, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LastName = "Martinez",
                            ManagerId = 2,
                            Position = "Marketing Manager",
                            Salary = 85000m
                        });
                });

            modelBuilder.Entity("GraphQL.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St, New York, NY",
                            ContactNumber = "+1-555-0101",
                            CreatedAt = new DateTime(2026, 1, 20, 5, 31, 17, 171, DateTimeKind.Utc).AddTicks(9139),
                            CreatedBy = "System",
                            Email = "john.doe@company.com",
                            FirstName = "John",
                            FullName = "John Doe",
                            LastName = "Doe",
                            Username = "john.doe"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Oak Ave, Los Angeles, CA",
                            ContactNumber = "+1-555-0102",
                            CreatedAt = new DateTime(2026, 1, 20, 5, 31, 17, 171, DateTimeKind.Utc).AddTicks(9143),
                            CreatedBy = "System",
                            Email = "jane.smith@company.com",
                            FirstName = "Jane",
                            FullName = "Jane Smith",
                            LastName = "Smith",
                            Username = "jane.smith"
                        });
                });

            modelBuilder.Entity("GraphQL.Models.Employee", b =>
                {
                    b.HasOne("GraphQL.Models.User", "Manager")
                        .WithMany("Employees")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("GraphQL.Models.User", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
